--- #YAML:1.0
name: Exception-Class-DBI
version: 0.91
license: perl
distribution_type: module
requires:
  DBI: 1.28
  Exception::Class: 1.02
recommends: {}
build_requires:
  Test::Harness: 2.03
  Test::Simple: 0.17
conflicts: {}
provides:
  Exception::Class::DBI:
    file: lib/Exception/Class/DBI.pm
    version: 0.91
generated_by: Module::Build version 0.19_05
