---
name: Exception-Class-DBI
version: 0.97
author:
  - 'David Wheeler <david@kineticode.com>'
abstract: DBI Exception objects
license: perl
resources:
  license: http://dev.perl.org/licenses/
configure_requires:
  Module::Build: 0.2701
requires:
  DBI: 1.28
  Exception::Class: 1.02
build_requires:
  Module::Build: 0.2701
  Test::Harness: 2.03
  Test::More: 0.17
recommends:
  Test::Pod: 1.20
provides:
  Exception::Class::DBI:
    file: lib/Exception/Class/DBI.pm
    version: 0.97
  Exception::Class::DBI::DBH:
    file: lib/Exception/Class/DBI.pm
  Exception::Class::DBI::H:
    file: lib/Exception/Class/DBI.pm
  Exception::Class::DBI::STH:
    file: lib/Exception/Class/DBI.pm
generated_by: Module::Build version 0.280801
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.2.html
  version: 1.2
