---
name: Exception-Class-DBI
version: !!perl/hash:Module::Build::Version
  original: 0.95
  version:
    - 0
    - 950
author:
  - 'David Wheeler <david@kineticode.com>'
abstract: DBI Exception objects
license: perl
resources:
  license: http://dev.perl.org/licenses/
requires:
  DBI: 1.28
  Exception::Class: 1.02
build_requires:
  Test::Harness: 2.03
  Test::Simple: 0.17
provides:
  Exception::Class::DBI:
    file: lib/Exception/Class/DBI.pm
    version: 0.95
  Exception::Class::DBI::DBH:
    file: lib/Exception/Class/DBI.pm
  Exception::Class::DBI::H:
    file: lib/Exception/Class/DBI.pm
  Exception::Class::DBI::STH:
    file: lib/Exception/Class/DBI.pm
generated_by: Module::Build version 0.2804
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.2.html
  version: 1.2
